apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # Listen for incoming requests.
      targetPort: 8080 # Forward traffic to the Pod. Must be identical to $containerPort in the Pod config.
